# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Conditional Kolmogorov-Smirnov distribution draw
#'
#' Follows the logistic regression, generates from the conditional
#' distribution of \eqn{\kappa} and \eqn{\lambda} given
#' the value of \eqn{R = |y - X\beta|} outlined in Appendix A.4 of Holmes and Held (2006)
#'
#' @param r vector of absolute value of centered augmented data
#' @return vector of scale parameters \eqn{\lambda}
#' @references Leonhard Held, Chris C. Holmes (2006). \emph{Bayesian auxiliary variable models for binary and multinomial regression}, Bayesian Analysis, 1(\bold{1}), 145-168.
logist_KS <- function(r) {
    .Call(`_hecbayes_logist_KS`, r)
}

